version: '3.7'

x-network:
  &network
  networks:
    - nxclient_website

services:
  traefik:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
    - 80:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    <<: *network
  
  php:
    image: quay.io/sylius/php:latest
    depends_on:
      - mysql
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@mysql/sylius_prod
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}
      - MAILER_URL=gmail://${MAILER_USER}:${MAILER_PASS}@localhost
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
    volumes:
      - ./:/srv/sylius:rw
    <<: *network

  mysql:
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=sylius_prod
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql:rw
    <<: *network

  nginx:
    image: quay.io/sylius/nginx:latest
    depends_on:
      - php
    volumes:
      - ./public/media:/srv/sylius/public/media:ro
    labels:
      - traefik.http.routers.nxclient-website-nginx.rule=Host(`${DOMAIN_NAME}`, `www.${DOMAIN_NAME}`)
    <<: *network

networks:
  nxclient_website:
    external: true

volumes:
  mysql-data: {}
  public-media: {}
